USE cs174;
DROP TABLE IF EXISTS user;
CREATE TABLE user (id INTEGER AUTO_INCREMENT PRIMARY KEY, username VARCHAR(256) UNIQUE NOT NULL, email VARCHAR(256) UNIQUE NOT NULL,
password CHAR(32) NOT NULL, salt CHAR(10) NOT NULL);
DROP TABLE IF EXISTS history;
CREATE TABLE history(id INTEGER AUTO_INCREMENT PRIMARY KEY, username VARCHAR(256) UNIQUE NOT NULL, input TEXT NOT NULL, cipher CHAR(64) NOT NULL, 
time TIMESTAMP NOT NULL);