USE cs174;
DROP TABLE IF EXISTS user;
CREATE TABLE user (id INTEGER AUTO_INCREMENT PRIMARY KEY, username VARCHAR(256) UNIQUE NOT NULL, email VARCHAR(256) UNIQUE NOT NULL,
password CHAR(32) NOT NULL, salt CHAR(10) NOT NULL);